alter table public.eva_demo_comments
  add column if not exists seq bigint generated by default as identity,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists eva_demo_comments_seq_key
  on public.eva_demo_comments (seq);

alter table public.eva_demo_comments
  drop constraint if exists eva_demo_comments_status_check;

alter table public.eva_demo_comments
  add constraint eva_demo_comments_status_check
  check (status in ('open', 'doing', 'asked', 'resolved', 'wontfix'));

create or replace function public.set_eva_demo_comment_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_eva_demo_comment_updated_at() from public, anon, authenticated;

drop trigger if exists set_eva_demo_comment_updated_at on public.eva_demo_comments;
create trigger set_eva_demo_comment_updated_at
before update on public.eva_demo_comments
for each row execute function public.set_eva_demo_comment_updated_at();

revoke update on public.eva_demo_comments from anon, authenticated;
grant update (status) on public.eva_demo_comments to anon, authenticated;

drop policy if exists "reviewers can change comment workflow status" on public.eva_demo_comments;
create policy "reviewers can change comment workflow status"
on public.eva_demo_comments for update
to anon, authenticated
using (true)
with check (status in ('open', 'doing', 'asked', 'resolved', 'wontfix'));

create table if not exists public.eva_demo_comment_replies (
  id uuid primary key default gen_random_uuid(),
  comment_id uuid not null references public.eva_demo_comments(id) on delete cascade,
  author_name text not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint eva_demo_comment_replies_author_name_length
    check (char_length(btrim(author_name)) between 2 and 40),
  constraint eva_demo_comment_replies_body_length
    check (char_length(btrim(body)) between 1 and 2000)
);

create index if not exists eva_demo_comment_replies_comment_created_idx
  on public.eva_demo_comment_replies (comment_id, created_at);

alter table public.eva_demo_comment_replies enable row level security;

revoke all on public.eva_demo_comment_replies from anon, authenticated;
grant select, insert on public.eva_demo_comment_replies to anon, authenticated;

drop policy if exists "eva comment replies are visible to reviewers" on public.eva_demo_comment_replies;
create policy "eva comment replies are visible to reviewers"
on public.eva_demo_comment_replies for select
to anon, authenticated
using (true);

drop policy if exists "reviewers can add constrained replies" on public.eva_demo_comment_replies;
create policy "reviewers can add constrained replies"
on public.eva_demo_comment_replies for insert
to anon, authenticated
with check (
  char_length(btrim(author_name)) between 2 and 40
  and char_length(btrim(body)) between 1 and 2000
);

comment on table public.eva_demo_comment_replies is
  'Append-only replies shared by reviewers of the public Eva prototype.';
